title: Brand New Product
email: acmegrouptest@gmail.com
description:
  We’ve launched a new product. Even if it is easy-to-use, we have decided to create a documentation website!
baseurl: ""
url: ""


# Build settings
sass:
  sass_dir: _sass
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
input: GFM